In [92]:
import open3d as o3d
import numpy as np
import os

# Load the mesh
mesh = o3d.io.read_triangle_mesh("ShapeNetCorev2/02871439/1ab8202a944a6ff1de650492e45fb14f/models/model_normalized.obj")

[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2
[Open3D INFO] Skipping non-triangle primitive geometry of type: 2


In [93]:
''' checks for mesh reading'''
# print(type(mesh))
# # mesh.compute_vertex_normals()
# abc =np.array(mesh.vertex_normals)
# print(abc[0])
# tolerance = 1e-6
# print(np.where(np.isclose(abc, -0.000538353, atol=tolerance)))
# print(mesh.vertices)
# print(mesh.triangles)
# # o3d.visualization.draw_geometries([mesh])

' checks for mesh reading'

In [94]:
base_pcd = np.array(mesh.vertices)
base_normals = np.array(mesh.vertex_normals)

In [95]:
np.array(mesh.triangles).max()

287

In [96]:
np.array(mesh.triangles)[:,2]

array([  2,   3,   6,   5,  10,  13,  16,  19,  22,  25,  28,  31,  32,
        12,  34,  18,  36,  24,  38,  30,  42,  45,  46,  44,  50,  51,
        54,  53,  58,  61,  64,  67,  70,  73,  76,  79,  80,  60,  82,
        66,  84,  72,  86,  78,  90,  93,  94,  92,  98,  99, 102, 101,
       106, 109, 112, 115, 118, 121, 124, 127, 128, 108, 130, 114, 132,
       120, 134, 126, 138, 141, 142, 140, 146, 147, 150, 149, 154, 157,
       160, 163, 166, 169, 172, 175, 176, 156, 178, 162, 180, 168, 182,
       174, 186, 189, 190, 188, 194, 195, 198, 197, 202, 205, 208, 211,
       214, 217, 220, 223, 224, 204, 226, 210, 228, 216, 230, 222, 234,
       237, 238, 236, 242, 243, 246, 245, 250, 253, 256, 259, 262, 265,
       268, 271, 272, 252, 274, 258, 276, 264, 278, 270, 282, 285, 286,
       284], dtype=int32)

In [97]:
tri_x = base_pcd[np.array(mesh.triangles)[:,0]] 
tri_y = base_pcd[np.array(mesh.triangles)[:,1]]
tri_z = base_pcd[np.array(mesh.triangles)[:,2]]

print(tri_x.shape == tri_y.shape == tri_z.shape)


norm_x = base_normals[np.array(mesh.triangles)[:,0]]
norm_y = base_normals[np.array(mesh.triangles)[:,1]]
norm_z = base_normals[np.array(mesh.triangles)[:,2]]

print(norm_x.shape == norm_y.shape == norm_z.shape)

True
True


In [79]:
# tri_x

In [118]:
# ans = np.cross(tri_x - tri_y, tri_x - tri_z, axis = 1)
# print(ans.shape, np.array(mesh.triangles).shape, tri_x.shape, tri_y.shape, tri_z.shape)

(4688, 3)

In [98]:
def area_calc(x,y,z):
    #using cross product
    return 0.5 * np.linalg.norm(np.cross(x-y, x-z), axis=1)

In [99]:
areas = area_calc(tri_x, tri_y, tri_z)
probs = areas/areas.sum()

In [100]:
(areas.shape)

(144,)

In [101]:
# weighted indices for the triangles/faces not the vertices
weighted_indices = np.random.choice(np.arange(areas.shape[0]), size=2048, p=probs)
weighted_indices

array([ 37, 132, 109, ..., 117, 124,   5])

In [102]:
tri_x = tri_x[weighted_indices]
tri_y = tri_y[weighted_indices]
tri_z = tri_z[weighted_indices]

norm_x = norm_x[weighted_indices]
norm_y = norm_y[weighted_indices]
norm_z = norm_z[weighted_indices]

In [103]:
a = np.random.randint(0, 100, size=(2048,1))
b = np.random.randint(0, 100, size=(2048,1))
c = np.random.randint(0, 100, size=(2048,1)) 

sum = np.sum([a,b,c], axis=0)
# print(sum.shape)
a = a/sum
b = b/sum
c = c/sum

# verify = np.sum([a,b,c], axis=0)
# print(verify)

In [104]:
sampled_pts = np.multiply(a, tri_x) + np.multiply(b, tri_y) + np.multiply(c, tri_z)
# sampled_pts.shape
#normalise the sampled pts

In [105]:
sampled_pts

array([[ 0.37229601,  0.10570121, -0.06482112],
       [ 0.23913159, -0.04595341,  0.107268  ],
       [-0.33998099, -0.047644  , -0.00072515],
       ...,
       [-0.34511633, -0.02844055, -0.140481  ],
       [-0.28563072, -0.09352933,  0.107268  ],
       [ 0.00296719, -0.294202  ,  0.09415959]])

In [88]:
base_pcd

array([[-0.33998099, -0.30968601,  0.107268  ],
       [ 0.37229601, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [ 0.37229601, -0.30968601,  0.107268  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [ 0.37229601, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.30968601,  0.107268  ],
       [ 0.37229601, -0.30968601,  0.107268  ],
       [ 0.37229601, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  , -0.140481  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  , -0.140481  ],
       [ 0.37229601, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  , -0.140481  ],
       [-0.33998099, -0.30968601,  0.107268  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.294202  ,  0.107268  ],
       [-0.33998099, -0.30968601,  0.107268  ],
       [-0.33998099, -0.294202  , -0.140481  ],
       [-0.33998099, -0.30968601,  0.107

In [106]:
stand_pcd = sampled_pts - np.mean(sampled_pts, axis=0)

In [107]:
stand_pcd

array([[ 0.3517961 ,  0.10398645, -0.09109924],
       [ 0.21863169, -0.04766816,  0.08098988],
       [-0.36048089, -0.04935876, -0.02700327],
       ...,
       [-0.36561623, -0.03015531, -0.16675911],
       [-0.30613062, -0.09524409,  0.08098988],
       [-0.01753271, -0.29591676,  0.06788147]])

In [110]:
pc1 = o3d.geometry.PointCloud()
pc1.points = o3d.utility.Vector3dVector(base_pcd)
# pc1.normals = o3d.utility.Vector3dVector(base_normals)
# pc1.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.1, max_nn=30))
# print(np.array(pc1.normals).shape, base_normals.shape)
# o3d.visualization.draw_geometries([pc1], point_show_normal=True)
pc1.normals = o3d.utility.Vector3dVector(base_normals*100)
o3d.visualization.draw_geometries([pc1], point_show_normal=True)
#

In [113]:
pc = o3d.geometry.PointCloud()
pc.points = o3d.utility.Vector3dVector(np.asarray(stand_pcd))
pc.normals = o3d.utility.Vector3dVector(np.asarray(sampled_norms)*50)
o3d.visualization.draw_geometries([pc], point_show_normal=True)


In [37]:
pc = o3d.geometry.PointCloud()
pc.points = o3d.utility.Vector3dVector(np.asarray(sampled_pts))
pc.estimate_normals(search_param=o3d.geometry.KDTreeSearchParamHybrid(radius=0.2, max_nn=30))
o3d.visualization.draw_geometries([pc], point_show_normal=True)


In [111]:
sampled_norms = np.multiply(a, norm_x) + np.multiply(b, norm_y) + np.multiply(c, norm_z)


In [21]:
sampled_norms = a*norm_x + b*norm_y + c*norm_z  

In [22]:
sampled_norms

array([[ 0.        ,  0.0254    ,  0.        ],
       [-0.01242661, -0.02201803,  0.00208852],
       [ 0.        ,  0.0254    ,  0.        ],
       ...,
       [ 0.        , -0.0254    ,  0.        ],
       [ 0.        ,  0.0254    ,  0.        ],
       [ 0.02493489,  0.00287943,  0.00208852]])

In [20]:
sampled_norms

array([[ 0.        ,  0.0254    ,  0.        ],
       [-0.01242661, -0.02201803,  0.00208852],
       [ 0.        ,  0.0254    ,  0.        ],
       ...,
       [ 0.        , -0.0254    ,  0.        ],
       [ 0.        ,  0.0254    ,  0.        ],
       [ 0.02493489,  0.00287943,  0.00208852]])

In [18]:
base_normals

array([[-0.0244351 ,  0.        ,  0.00693443],
       [-0.024668  ,  0.        ,  0.00605373],
       [-0.024668  ,  0.        ,  0.00605373],
       ...,
       [ 0.00291041,  0.00184846,  0.0251649 ],
       [ 0.0252105 ,  0.00084981, -0.0029781 ],
       [ 0.0252105 ,  0.00084981, -0.0029781 ]])

In [148]:
#method 2

sum_norm = np.sum([norm_x, norm_y, norm_z], axis=0)
# sum_norm.shape
sampled_norms2 = sum_norm/np.linalg.norm(sum_norm, axis=1).reshape(-1,1)
sampled_norms2.astype(np.float32)

print(sampled_norms2.shape)

(2048, 3)


In [38]:
print("Testing mesh in Open3D...")
armadillo_mesh = o3d.data.ArmadilloMesh()
mesh = o3d.io.read_triangle_mesh(armadillo_mesh.path)

knot_mesh = o3d.data.KnotMesh()
mesh = o3d.io.read_triangle_mesh(knot_mesh.path)
print(mesh)
print('Vertices:')
print(np.asarray(mesh.vertices))
print('Triangles:')
print(np.asarray(mesh.triangles))

Testing mesh in Open3D...
[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/ArmadilloMesh.ply
[Open3D INFO] Downloaded to /home/cvig_5/open3d_data/download/ArmadilloMesh/ArmadilloMesh.ply
[Open3D INFO] Downloading https://github.com/isl-org/open3d_downloads/releases/download/20220201-data/KnotMesh.ply
[Open3D INFO] Downloaded to /home/cvig_5/open3d_data/download/KnotMesh/KnotMesh.ply
TriangleMesh with 1440 points and 2880 triangles.
Vertices:
[[  4.51268387  28.68865967 -76.55680847]
 [  7.63622284  35.52046967 -69.78063965]
 [  6.21986008  44.22465134 -64.82303619]
 ...
 [-22.12651634  31.28466606 -87.37570953]
 [-13.91188431  25.4865818  -86.25827026]
 [ -5.27768707  23.36245346 -81.43279266]]
Triangles:
[[   0   12   13]
 [   0   13    1]
 [   1   13   14]
 ...
 [1438   11 1439]
 [1439   11    0]
 [1439    0 1428]]
